### PR TITLE
API cleanup

### PR DESCRIPTION
**Pull request by kkrampa**
Removed unused apis, added ordering and filtering on some fields.

### CODE REVIEW

**Comment by czue** [comment]
do you need this deployed?

**Comment by rowenaluk** [comment]
deployed

On Sat, Aug 1, 2015 at 11:08 AM, Cory Zue <notifications@github.com> wrote:

> do you need this deployed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/logistics/pull/222#issuecomment-126889472>.
>



-- 
Rowena Luk
VP of Strategy
Dimagi, Inc.

Skype: rowenaluk
Cape Town: +27 79 908 3304
Senegal: +221 78 291 23 25
USA: +1 857 919 5178

**Comment by kkrampa** [comment]
@rowenaluk @czue I think Rowena deployed EWS changes not this one. Could you deploy this changes to ILS, please?

**Comment by czue** [comment]
yes, will do

**Comment by czue** [comment]
deployed (sorry for long delay)

**Pull request merged**
