### PR TITLE
Speed up Message Log

### PR DESCRIPTION
**Pull request by gcapalbo**
@czue i did some digging and was about to put a fix but looks like you already fixed this in https://github.com/dimagi/djtables/pull/1. (i was going to make the same fix)

so all that's needed here is to update submodules

### CODE REVIEW

**Comment by czue** [comment]
hahaha how bout that.

**Comment by czue** [comment]
thanks for tracking that down! looks like there were a few other changes in the djtables update. confirming no issues?

**Comment by gcapalbo** [comment]
yeah i looked through the other changes made by the djtables update and they seemed fine to me. there was only one other big change which was to allow jumping to a page in a table, but that was put behind an option that is set to False by default. the rest of the changes were minor css changes. but i clicked through the reports to be safe and everything looked ok

**Comment by czue** [comment]
:+1: great, thanks.

**Pull request merged**
