### PR TITLE
runner cleanup

### PR DESCRIPTION
**Pull request by czue**
pulls out all the closure functions into module level functions that take in the arguments they need

review by commit. @gcapalbo 

this contains one commit each from https://github.com/dimagi/logistics/pull/245 and https://github.com/dimagi/logistics/pull/246 though I think they should just merge in cleanly

### CODE REVIEW

**Comment by jpwagner** [comment]
nice

**Comment by czue** [comment]
lol, hi @jpwagner !

**Comment by gcapalbo** [comment]
looks ok to me, is there test coverage on this?

also it looks like there are merge conflicts after merging #246. might want to wait until #245 gets merged before fixing those.

**Comment by czue** [comment]
@gcapalbo rebased on malawi-dev.

unfortunately there is no test coverage, though I think I was pretty careful and the majority of the changes are just moving code around. I also did run the warehouse locally off a tiny data set and it completed successfully. and then I intentionally introduced an error and confirmed it broke (just to confirm the new logic was being called). I will get notified if there are any errors the next time the warehouse updates and those can always be fixed, so I feel ok merging and addressing anything that comes up.

**Pull request merged**
