### PR TITLE
Added csv to move locations from Mufindi

### PR DESCRIPTION
**Pull request by kkrampa**
@gcapalbo @czue 
http://manage.dimagi.com/default.asp?217228#1094028

Could you run this command on prod?
```./manage.py tz_move_locations apps/tanzania/management/commands/resource/MafingaTC.csv --byname --dryrun```

### CODE REVIEW

**Comment by gcapalbo** [comment]
@czue Kamil mentioned there might be a certain time that this command should be run so as not to interfere with other operations.  Do you know when that time is, and if it's in your timezone can you run it? Otherwise let me know what time and I can run it.

**Comment by czue** [comment]
@gcapalbo I think the main thing would be to run it at a time where we don't expect it to get interrupted (e.g. by a deploy). so right after a prod deploy or in the morning in india would be good. I don't think it will take crazy long (maybe 30 minutes or something?) @kkrampa - do you want just the `--dryrun` output, or do you actually want it run on prod?

**Comment by czue** [comment]
oh, sorry, I was confused about which repo this was. we should run it when the warehouse isn't running, which can be checked here: http://ilsgateway.com/django-admin/warehouse/reportrun/

probably late in the day in boston is best

**Comment by czue** [comment]
(if it's not done by EOD today then you can ping me and i'll run it first thing tomorrow morning in india)

**Comment by gcapalbo** [comment]
@czue ok, i'll run it later today
@kkrampa see @czue's comment above - is `./manage.py tz_move_locations apps/tanzania/management/commands/resource/MafingaTC.csv --byname --dryrun` the right command to run, including the `--dryrun` option?

**Comment by kkrampa** [comment]
yep, we need to run this with --dryrun option. Not sure that I understand Cory, but with dryrun reporting data will be also recalculated.

**Comment by gcapalbo** [comment]
(kicking this off now)

**Comment by czue** [comment]
@kkrampa I think it's the other way around. if you pass --dryrun it just prints results and doesn't actually run/save anything.

https://github.com/dimagi/logistics/blob/tz-master/logistics_project/apps/tanzania/management/commands/tz_move_locations.py#L69
https://github.com/dimagi/logistics/blob/tz-master/logistics_project/apps/tanzania/management/commands/tz_move_locations.py#L73

**Comment by gcapalbo** [comment]
ok, i haven't run the command yet.  @kkrampa can you have a look at the management command code and confirm which options need to be added? i will hold off on running until we confirm.

@czue i've got a screen session setup with the application ssh user's account that's all ready to go (code is updated, in the right dir, virtual env, etc., just need to run the command). it looks like the warehouse report runner runs every day at 9am UTC.  if we confirm the right command in time, would you mind just logging into the screen session and kicking it off?  if it gets to be too close timewise, no problem, i'll run this tomorrow night

**Comment by kkrampa** [comment]
@gcapalbo @czue 
Sorry for confusion. You are absolutely right. It should be run without --dryrun option. I think good idea is to run this with --dryrun option to check that everything is ok and then without --dryrun option.

**Comment by czue** [comment]
hey, sorry, I was in meetings all morning and didn't get to this in time.

**Comment by gcapalbo** [comment]
@kkrampa ok, thanks for confirming
@czue no worries, i'll run this tonight

**Comment by gcapalbo** [comment]
just ran this, looks ok but had one question - sent to both of you over email

**Pull request merged**
