### PR TITLE
Changes in api

### PR DESCRIPTION
**Pull request by kkrampa**

### CODE REVIEW

**Comment by czue** [comment]
@kkrampa ping @rowenaluk if you need this deployed

**Comment by rowenaluk** [comment]
@modonnell729 deployed

**Comment by kkrampa** [comment]
@rowenaluk Are you sure that newest changes are deployed? I added way to use lte filter on date but api still raises exception: ```"error": "'lte' is not an allowed filter on the 'date' field."```

**Comment by rowenaluk** [comment]
iconfirm it was deployed

On Tue, Jun 2, 2015 at 9:37 AM, Kamil Krampa <notifications@github.com>
wrote:

> @rowenaluk <https://github.com/rowenaluk> Are you sure that newest
> changes are deployed? I added way to use lte filter on date but api still
> raises exception: "error": "'lte' is not an allowed filter on the 'date'
> field."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/logistics/pull/219#issuecomment-107840815>.
>



-- 
Rowena Luk
VP of Strategy
Dimagi, Inc.

Skype: rowenaluk
Cape Town: +27 79 908 3304
Senegal: +221 78 291 23 25
USA: +1 857 919 5178

**Pull request merged**
