### PR TITLE
ILS: Added date_updated to logistics profile model

### PR DESCRIPTION
**Pull request by kkrampa**
@czue http://manage.dimagi.com/default.asp?189579#1062248

### CODE REVIEW

**Comment by kkrampa** [comment]
needs migration

**Comment by kkrampa** [comment]
@czue 
Could you merge this and deploy? (I think #235 is also not deployed)
Thanks!

**Comment by gcapalbo** [comment]
looks good to me, @czue i'm going to merge and deploy so we don't block, but once you get back if you don't mind taking a quick look over this pr that would be great

**Comment by gcapalbo** [comment]
@kkrampa this has been deployed

**Comment by czue** [comment]
thanks @gcapalbo! I looked at the code and it looked good, i just was holding off to make sure there weren't any issues with the DB migration. thanks for taking care of that

**Pull request merged**
